### ISSUE TITLE
backend redefine warnings

### ISSUE THREAD

**Issue by ayrat555** [elixir-cldr/cldr#130]
I compile my app with `compile --warnings-as-errors`

If I use any of the backends, for example `ex_cldr_units`. I'm getting
```
warning: redefining module BlockScoutWeb.Cldr.Number (current version loaded from /home/ayrat/Development/rockn/blockscout/_build/dev/lib/block_scout_web/ebin/Elixir.BlockScoutWeb.Cldr.Number.beam)
  lib/block_scout_web/cldr.ex:
```
which fails compilation

**Comment by kipcole9** [comment]
Thanks for the report.  Can you let me know:
1. The version of `ex_cldr` and of the dependent packages you are using?
2. An example backend configuration the error?
3. The warning is always on `*.Cldr.Number` ?

That way I can build a simple test case to see how the issue arises.

**Comment by ayrat555** [comment]
1. {:ex_cldr, "~> 2.0"} -> `2.7.0`
2. dependent package is `{:ex_cldr_units, "~> 2.5"}`
configuration module
```
defmodule BlockScoutWeb.Cldr do
  use Cldr,
    default_locale: "en",
    locales: ["en"],
    gettext: BlockScoutWeb.Gettext,
    generate_docs: false
end
```
3. yes

**Comment by kipcole9** [comment]
Thanks much, I'll work on this over the next 12 hours.  Sorry for the inconvenience.

**Comment by kipcole9** [comment]
May I also suggest update to [ex_cldr version 2.7.2](https://github.com/elixir-cldr/cldr/releases/tag/v2.7.2) which fixes an issue related to `Gettext` configuration in `ex_cldr` backend modules.

**Comment by ayrat555** [comment]
I tried it with no success

**Comment by kipcole9** [comment]
Hmmm, I'm not seeing the same symptoms as you. I have created the simplest repo I can at https://github.com/elixir-cldr/cldr_issue_130

If you have an opportunity, could you clone it and compile and see if you are getting the same warning result?  I hard coded the current releases to be deterministic.  I also added:
```
use Cldr,
  ...
  providers: [Cldr.Number, Cldr.Unit]
```
Although removing it has no noticeable difference other than silencing some console logging at compiler time.

**Comment by ayrat555** [comment]
`cldr_issue_130` is compiling without any warnings. I tried setting exactly the same deps versions but again the warning appears.
Also, I tried to configure the library with `otp_app` option. no success.

Maybe the issue is related to umbrella applications?

**Comment by kipcole9** [comment]
Any possibility you can give me access to your repo?  I appreciate the answer may be "no" for confidentiality reasons, but it would certainly make it easier for me to work on the issue.  I can't think of why an umbrella app would make a difference.

**Comment by ayrat555** [comment]
no problem. it's here https://github.com/poanetwork/blockscout/pull/2473

**Comment by kipcole9** [comment]
I believe the issue is that you are defining your own `BlockScoutWeb.Cldr.Number` module in `block_scout_web/views/cldr/number.ex`. This clashes with the generated module that comes from 
```elixir
defmodule BlockScoutWeb.Cldr do
  use Cldr,
    default_locale: "en",
    locales: ["en"],
    gettext: BlockScoutWeb.Gettext,
    generate_docs: false,
    providers: [Cldr.Number, Cldr.Unit]
end
```

You note that you see a bug in `Cldr.Number.to_string!/3`.  Let me know what the wrong behaviour is and I'll work on fixing that.

**Comment by kipcole9** [comment]
I also recommend changing
```elixir
config :ex_cldr,
  default_locale: "en",
  locales: ["en"],
  gettext: BlockScoutWeb.Gettext
```
to
```elixir
config :ex_cldr,
  default_locale: "en"
```
in `apps/config/config.exs`

**Comment by kipcole9** [comment]
Oh, I see that your private `BlockScoutWeb.Cldr.Niumber` module was working around some old dialyzer errors.  `ex_cldr` and friends now all pass dialyzer so I wouldn't expect you to need this module any more.

**Comment by ayrat555** [comment]
@kipcole9 thanks. the issue was in the conflicting module name. renaming it fixed the issue
