### ISSUE TITLE
[Spellout] Do not support for float number

### ISSUE THREAD

**Issue by quan-nh2** [elixir-cldr/cldr#143]
### Code: 
```elixir
MyAdmin. Cldr.Number.to_string 1234.4, format: :spellout

{:error,
 {Cldr.Rbnf.NoRuleForNumber,
  "rule group :spellout_numbering for locale \"en\" does not know how to process 1234.4"}}
```

Could you support convert from float numbers to words in the future? Thank you!

**Comment by kipcole9** [comment]
Thanks for the issue. The [Rules Based Number Formats (RBNF)](https://unicode.org/reports/tr35/tr35-numbers.html#Rule-Based_Number_Formatting) are not always complete for floating point numbers for all locales and there isn't an easy way to introspect the rules either.

However for the "en" locale, the ruleset `:spellout_cardinal` does implement floating point support.  So for example:
```elixir
iex> Cldr.Number.to_string 1234.4, format: :spellout_cardinal, locale: "en"        
{:ok, "one thousand two hundred thirty-four point four"}

# Just notices that this format was not in the `Cldr.Number.to_string/3` api
# So I have added it and it will be published in the next version in April with
# CLDR 39 data.
iex> Cldr.Number.to_string 1234.4, format: :spellout_cardinal_verbose, locale: "en"
{:ok, "one thousand two hundred and thirty-four point four"}
```
Hopefully this fulfils your immediate need - please let me know if not!

**Comment by quan-nh2** [comment]
So great! Thanks for you support!
