### ISSUE TITLE
Mistakes in DEVELOPMENT.md

### ISSUE THREAD

**Issue by josevalim** [elixir-cldr/cldr#160]
Hi @kipcole9,

I am going through DEVELOPMENT.md and I believe it must be outdated in some places.

1. `export $CLDR_REPO` must not have the `$` character

2. Some commands use `MIX_ENV=gen` but there is no such environment

3. Step "Download the up-to-date ISO currency database" does not work at that moment. I have skipped it for now.

I will drop more comments/edit as I run into things.

**Comment by kipcole9** [comment]
My apologies José, I have updated DEVELOPMENT.md (thanks for the edits) and had to adjust one of the environment compile paths. I have pushed a commit which, I think, means all is aligned again.

**Comment by josevalim** [comment]
Beautiful, thank you! :heart:
