### ISSUE TITLE
Error downloading *.json files due to missing release tag on github for v2.24.2

### ISSUE THREAD

**Issue by seantanly** [elixir-cldr/cldr#163]
Unable to download JSON files for v2.24.2. It seems to be due to the missing release tag on Github. 

Version 2.24.1 - works
https://raw.githubusercontent.com/elixir-cldr/cldr/v2.24.1/priv/cldr/locales/en.json

Version 2.24.2 - fails with 404
https://raw.githubusercontent.com/elixir-cldr/cldr/v2.24.2/priv/cldr/locales/en.json

**Comment by kipcole9** [comment]
@seantanly, apologies for the inconvenience - you are right, I  hadn't tagged the release. Now done.

**Comment by seantanly** [comment]
Thank you @kipcole9 for responding swiftly 👍
