### ISSUE TITLE
RBNF missing after upgrading

### ISSUE THREAD

**Issue by juanperi** [elixir-cldr/cldr#175]
I've updated from 2.25.2 to 2.26.0, and suddenly I started seeing the following error for `nb` locale:
```
iex(1)> IO.inspect(SylarLocalization.Cldr.put_locale("nb"), structs: false)
{:ok,
 %{
   __struct__: Cldr.LanguageTag,
   backend: SylarLocalization.Cldr,
   canonical_locale_name: "nb",
   cldr_locale_name: :nb,
   extensions: %{},
   gettext_locale_name: "nb",
   language: "nb",
   language_subtags: [],
   language_variants: [],
   locale: %{},
   private_use: [],
   rbnf_locale_name: nil,
   requested_locale_name: "nb",
   script: :Latn,
   territory: :NO,
   transform: %{}
 }}
{:ok, #Cldr.LanguageTag<nb [validated]>}
iex(2)> SylarLocalization.Cldr.Number.to_string(1234)
{:error, {Cldr.Rbnf.NotAvailable, "RBNF is not available for the locale :nb"}}
```
This was not happening in the previous version, though, where I would get:
```
iex(1)> IO.inspect(SylarLocalization.Cldr.put_locale("nb"), structs: false)
{:ok,
 %{
   __struct__: Cldr.LanguageTag,
   backend: SylarLocalization.Cldr,
   canonical_locale_name: "nb",
   cldr_locale_name: :nb,
   extensions: %{},
   gettext_locale_name: "nb",
   language: "nb",
   language_subtags: [],
   language_variants: [],
   locale: %{},
   private_use: [],
   rbnf_locale_name: :nb,
   requested_locale_name: "nb",
   script: :Latn,
   territory: :NO,
   transform: %{}
 }}
{:ok, #Cldr.LanguageTag<nb [validated]>}
iex(2)> SylarLocalization.Cldr.Number.to_string(1234)
{:ok, "1¬†234"}
```

Is this a bug? or is it related to the upgrade to release 41 (Update [CLDR](https://cldr.unicode.org) to [release 41] as per the changelog) and it is expected that we might lose access to localized numbers after cldr releases update?

Thank you very much for your help figuring this out!!

**Comment by kipcole9** [comment]
@juanperi , as of [commit 3ad972](https://github.com/elixir-cldr/cldr/commit/3ad972b0bb8e5534b84c90f9e546245ffcd260db), RBNF locale name resolution now inherits from a parent locale if there is one (and the parent for "nb" is "no" which does have RBNF data).  [Commit 687fb5](https://github.com/elixir-cldr/cldr/commit/687fb533fa3cd55941b2c6706accc9fab3bf264a) regenerates the known language tags and adds a test.

All tests pass so I am ready to release `ex_cldr` version `2.29.0` if you are comfortable that the RBNF for "no" is acceptable for locale "nb".

**Comment by kipcole9** [comment]
Turns out it wasn't that difficult to fix. But I greatly appreciate the encouragement, it really helps with motivation.

I have published [ex_cldr version 2.29.0](https://hex.pm/packages/ex_cldr/2.29.0) with the following changelog entry:
```elixir
### Migration

* The plugs `Cldr.Plug.SetLocale`, `Cldr.Plug.AcceptLanguage` and `Cldr.Plug.PutSession` have been extracted to their own library, [ex_cldr_plug](https://hex.pm/packages/ex_cldr_plug). Therefore adding `{:ex_cldr_plug, "~> 1.0"}` to the `deps` of any application using these plugs is required.

### Bug Fixes

* Fixes resolving the RBNF locale name for locales that inherit the RBNF locale from a parent. This is true for at least the "nb" locale which in previous releases had its own RBNF locale data but now inherits from "no". Thanks to @juanperi for the report. Closes [#175](https://github.com/elixir-cldr/cldr/issues/175).
```
I'll leave this issue open for a little bit in case there is an issue I didn't find in testing.

Appreciate your collaboration!

**Comment by juanperi** [comment]
in production already! working as expected!!

thank you very much!


have a nice day 😊

**Comment by kipcole9** [comment]
Great to hear, thanks for the feedback. Closing!
