### ISSUE TITLE
Cannot compile v2.31.0

### ISSUE THREAD

**Issue by dolfinus** [elixir-cldr/cldr#179]
I've updated package version to 2.31.0, but got a complation error:
```
==> linguist
Compiling 5 files (.ex)
Error: 7.621 [error] Failed to download locale :ru from https://raw.githubusercontent.com/elixir-cldr/cldr/v2.31.0/priv/cldr/locales/ru.json. HTTP Error: (404) 'Not Found'
Generating Linguist.Cldr for 3 locales named [:en, :ru, :und] with a default locale named :en
```

This is because tag `v2.31.0` is missing in the repo

**Comment by dolfinus** [comment]
@kipcole9 Could you please take a look?

**Comment by kipcole9** [comment]
My apologies, thats very sloppy of me.  Release tag added.

**Comment by dolfinus** [comment]
Maybe the release process should be changed to avoid such issues? For example, make build and push package after a git tag is been pushed
