### ISSUE TITLE
Documentation - typos in readme file

### ISSUE THREAD

**Issue by SebastienPlourde** [elixir-cldr/cldr#183]
Hi,

Not a big deal but for those like me who do copy&paste of config

In 
`def deps do
  [
    {:ex_cldr, "~> 2.29},
    {:ex_cldr_plugs, "~> 1.0"},
    ...
  ]
end
 `

We should read 

`def deps do
  [
    {:ex_cldr, "~> 2.29"},
    {:ex_cldr_plugs, "~> 1.0"},
    ...
  ]
end
 `
Notice the " is missing.

**Comment by kipcole9** [comment]
Thanks for the report, fixed now and updated docs have been published.
