### ISSUE TITLE
Typo: Tetritory should be Territory

### ISSUE THREAD

**Issue by ericfjosne** [elixir-cldr/cldr#189]
At the following line, there is a typo in the word "Territory".
https://github.com/elixir-cldr/cldr/blob/d1973c101bd9ea72e32c76702aecc1a71c7984ef/lib/cldr/locale.ex#L15

Should be
`  * a Language code and Territory code such as `en-GB``

**Comment by kipcole9** [comment]
Thanks very much for the issue, much appreciated.
