### ISSUE TITLE
Character Direction attribute for languages/scripts.

### ISSUE THREAD

**Issue by Doerge** [elixir-cldr/cldr#196]
Hi,

I want to render right-to-left (rtl) languages properly in my frontend with the css `direction` property. My content is dynamic: I have the language code, but I need to figure out if it is rtl or not. I hoped to find that data somewhere in `ex_cldr_language`, but after digging around a bit, I _think_ it's not available in that repo, because it's not available here.

I tried looking for this data elsewhere, but it's not in BCP47 (that this repo already uses) or in [https://en.wikipedia.org/wiki/ISO_15924](ISO_15924).
I found it in [CLDR Json repository](https://github.com/unicode-org/cldr-json/blob/f27f55f1dd487af7cf4260f56296ee1c7649b7fc/cldr-json/cldr-misc-full/main/yi/layout.json#L12), but `ex_cldr` uses [CLDR repository](https://github.com/unicode-org/cldr) where I can't find it 😅 

Do you think it is viable to work this feature into this project, or is it outside the scope and should live in another project?

**Comment by kipcole9** [comment]
@Doerge thanks for the issue. Definitely in scope. And you're right, its not easy to track down in the CLDR repository (I haven't found it yet). However since the `cldr-json` repository is generated from `cldr` (and I also do the same under the covers) it must be there somewhere and I just have to find it.

I am due to release a beta of `ex_cldr version 2.37.0` based upon CLDR 43 by the end of this week and I will make sure to include language direction in it somehow.

**Comment by Doerge** [comment]
Found it now in the CLDR Repo by ripgrepping it locally. Githubs search is broken. The repo is too big.
[It is in common/main/<lang>.xml](https://github.com/unicode-org/cldr/blob/8f04544c6f31812a6bfd2fecc6ca6d2fd715771a/common/main/ar.xml#L1218)
```xml
	<layout>
		<orientation>
			<characterOrder>right-to-left</characterOrder>
		</orientation>
	</layout>
```

**Comment by kipcole9** [comment]
Yep, found the same. As of [commit 3fd958833]( https://github.com/elixir-cldr/cldr/commit/3fd95883325addd55313112eee27c5d73e05aa49) the layout info (text direction, line direction) are added to the locale files.  The API to expose these data is not yet in place - coming up next.

**Comment by kipcole9** [comment]
Thanks for the collaboration and suggestion.  This will ship with the next version of `ex_cldr` that will be in release candidate form by the end of this week.

**Comment by Doerge** [comment]
You're amazing Kip! Thanks so much for maintaining these important packages for the community!

**Comment by florianb** [comment]
Fantastic!
