### ISSUE TITLE
Recompiling every time?

### ISSUE THREAD

**Issue by bortzmeyer** [elixir-cldr/cldr#200]
Apparently, each time, I `mix run`, everything is recompiled (with the time it takes) eve,n if I changed nothing in the source code.

`mix.exs`:

```
  defp deps do
    [
      {:jason, "~> 1.0"},
      {:ex_cldr_numbers, "~> 2.30"}
    ]
  end
```

`lib/test_cldr.ex`:

```
defmodule MyApp.Cldr do
  use Cldr,
    locales: ["en", "fr"],
    default_locale: "fr",
    providers: [Cldr.Number]
end

defmodule TestCldr do
  def hello do
    
  end
end
```

` mix run lib/test_cldr.ex` always recompile (with a lot of warnings, see #199):

```
...
Generating MyApp.Cldr for 3 locales named [:en, :fr, :und] with a default locale named :fr
...
```

``` 
% elixir --version           
Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.12.2 (compiled with Erlang/OTP 24)
```

**Comment by kipcole9** [comment]
Glad that's cleared up the issue. Not sure what your use case is, doing `mix run lib/.....exs` isn't that common. If there's anything you need clarification on feel free to start a GitHub discussion and I'm happy to help.
