### ISSUE TITLE
unknown locale: lah

### ISSUE THREAD

**Issue by petrus-jvrensburg** [elixir-cldr/cldr#206]
Not sure if this is a bug, but when querying language population info using `ex_cldr_territories`
```
Cldr.Territory.info(:pak)
```
the response includes the "lah" group of languages, with a very high number of native speakers
```
"lah" => %{population_percent: 40}
```

But, when trying to add this to the `ex_cldr` backend as a supported locale, I get this error:
```
** (Cldr.UnknownLocaleError) Failed to install the locale named :lah. The locale name is not known.
```

**Comment by kipcole9** [comment]
In this case the error is correct. There is no locale `lah` in CLDR. There is no guarantee that all data cross-links. There isn't even a guarantee that all locales have the same data fields populated. Different locales have different levels of completion.

**Comment by petrus-jvrensburg** [comment]
Thanks
