### ISSUE TITLE
Dialyzer error: overlapping contract

### ISSUE THREAD

**Issue by AntoineAugusti** [elixir-cldr/cldr#236]
While trying to perform dependency upgrades, I encountered the following Dialyzer error.

https://github.com/etalab/transport-site/pull/4101

Versions:

- ex_cldr: 2.40.0
- ex_cldr_currencies: 2.16.1
- ex_cldr_numbers: 2.33.1
- cldr_utils: 2.28.0

```
lib/cldr.ex:1:overlapping_contract
Overloaded contract for Transport.Cldr.Currency.currencies_for_locale/3 has
overlapping domains; such contracts are currently unsupported and
are simply ignored.

________________________________________________________________________________
lib/cldr.ex:1:overlapping_contract
Overloaded contract for Transport.Cldr.Number.Format.all_formats_for/1 has
overlapping domains; such contracts are currently unsupported and
are simply ignored.
```

Our [Cldr backend](https://github.com/etalab/transport-site/blob/master/apps/shared/lib/cldr.ex).

Did I miss anything in the upgrade process or is this a bug?

**Comment by AntoineAugusti** [comment]
## Currency
Duplicate contracts for `currencies_for_locale/3`

https://github.com/elixir-cldr/cldr_currencies/blob/b666fe60786dddda72ecba8a3d6ebb50b4c1075c/lib/cldr/backend.ex#L449-L456

https://github.com/elixir-cldr/cldr_currencies/blob/b666fe60786dddda72ecba8a3d6ebb50b4c1075c/lib/cldr/backend.ex#L673

The second one seems to miss a bang `!`.

## Number

https://github.com/elixir-cldr/cldr_numbers/blob/5a51cccbb4288bebb7da75a7d7cb2678e6c7d939/lib/cldr/number/backend/format.ex#L157

https://github.com/elixir-cldr/cldr_numbers/blob/5a51cccbb4288bebb7da75a7d7cb2678e6c7d939/lib/cldr/number/backend/format.ex#L385

Missing a bang `!` as well for `all_formats_for/1`

**Comment by kipcole9** [comment]
I've published updates with your PRs for `ex_cldr_currencies` and `ex_cldr_numbers`. Let me know if that now resolves this issue?

**Comment by AntoineAugusti** [comment]
https://github.com/etalab/transport-site/pull/4101/commits/c5af596bd429ea24175bfa765b347719f7855ccc fixes the Dialyzer error, thanks a lot for handling this issue quickly and crafting releases!

All the best 🙏🌞
