### ISSUE TITLE
Q: why is dialyzer failing?

### ISSUE THREAD

**Issue by elvanja** [elixir-cldr/cldr#237]
Hi,

Trying to fix dialyzer error:

```
lib/admin_web/cldr.ex:1:missing_range
The type specification is missing types returned by function.

Function:
AdminWeb.Cldr.Calendar.localize/2

Type specification return types:

{:error, :incompatible_calendars | {atom(), binary()}}
| {:ok,
%Date{
:calendar => atom(),
:day => pos_integer(),
:month => pos_integer(),
:year => integer()
}}


Missing from spec:
binary()

________________________________________________________________________________
lib/admin_web/cldr.ex:1:missing_range
The type specification is missing types returned by function.

Function:
AdminWeb.Cldr.DateTime.Format.date_available_formats/2

Type specification return types:
{:ok, map()}

Missing from spec:
{:error, {atom(), binary()}}

________________________________________________________________________________
lib/admin_web/cldr.ex:1:missing_range
The type specification is missing types returned by function.

Function:
AdminWeb.Cldr.DateTime.Format.time_available_formats/2

Type specification return types:
{:ok, map()}

Missing from spec:
{:error, {atom(), binary()}}

________________________________________________________________________________
```

And related module that exhibits the error:

```elixir
defmodule AdminWeb.Cldr do
  use Cldr,
    default_locale: "en",
    locales: ["en"],
    providers: [Cldr.Number, Cldr.Calendar, Cldr.DateTime]

  defmodule Helpers do
    alias Web.Cldr.DateTime.Relative

    #@typep options :: Keyword.t() | map()
    
    #@spec time_ago(DateTime.t()) :: String.t() | no_return()
    def time_ago(datetime) do
      datetime
      |> DateTime.diff(DateTime.utc_now(), :second)
      |> Relative.to_string!()
    end

    #@spec format_datetime(Cldr.Calendar.any_date_time(), options()) :: String.t() | no_return()
    def format_datetime(datetime, options \\ []) do
      AdminWeb.Cldr.DateTime.to_string!(datetime, options)
    end
  end
end
```

Tried to force specs (commented out) but I get the same result.
Versions used:
- ex_cldr: 2.40.0
- ex_cldr_calendars: 1.26.0
- ex_cldr_currencies: 2.16.2
- ex_cldr_dates_times: 2.20.2
- ex_cldr_numbers: 2.33.2
- cldr_utils: 2.28.1

Any ideas?

**Comment by elvanja** [comment]
This is the setup:
```
      dialyzer: [
        # We also add `:iex` and `:aws_credentials` below.
        plt_add_apps: [:dialyxir_vendored, :debugger, :dialyzer, :ex_unit, :hex, :mix, :iex, :aws_credentials],
        flags: [
          # enable only to verify error handling
          # :unmatched_returns,
          :error_handling,
          :unknown,
          :underspecs,
          :extra_return,
          :missing_return
        ]
      ]
```

And no worries, this is not an emergency so please enjoy the weekend without Dialyzer issues 😄 🙇🏼

**Comment by kipcole9** [comment]
That is the most comprehensive dialyzer config I've seen. I'll definitely make sure that `:underspecs` and the default `:unknown` are warning free but I can't guarantee the others.

I've found one missing spec in `ex_cldr_calendars` so that's progress. The other warnings come from `ex_cldr_dates_times` so that's next.  

I don't like bugs lingering, they disturb my karma. :-)

**Comment by kipcole9** [comment]
I've made some progress, but not finished yet.

* All the libs I'm touching now use your dialyzer configuration of:

```
        flags: [
          :error_handling,
          :unknown,
          :underspecs,
          :extra_return,
          :missing_return
        ]
```

* I have updated and published releases for `ex_cldr`, `ex_cldr_numbers`, `ex_cldr_lists`,
* I have updated, but not published releases yet for `ex_cldr_calendars` and `ex_cldr_dates_times`
* I have not updated (yet) `ex_cldr_units` upon which `ex_cldr_calendars` and `ex_cldr_dates_times` depend. That's the last lib in the dependency tree before it's ready for you to properly test.  I will get this done over the weekend. For now, I've had enough of dialyzer. For some reason, over 90% of the issues raised on `ex_cldr_*` libs are `dialyzer` related. So the work to do this remediation is worth it on that basis alone.

**Comment by kipcole9** [comment]
I have now updates `ex_cldr_units`, `ex_cldr_calendars` and `ex_cldr_dates_times`.  This should complete the cycle for any of the `cldr_*` libs related to this issue.

@elvanja, Would you please update your dependencies and let me know if dialyzer, with your configuration, is now happy?

**Comment by elvanja** [comment]
Hi @kipcole9, good news, Dialyzer is green again 😄
Appreciate all this tedious work 🙇🏼
