### ISSUE TITLE
For nan-TW, script should be "Hant"

### ISSUE THREAD

**Issue by logicmason** [elixir-cldr/cldr#45]
The locale "nan-tw", refers to the Taiwanese language (also known as Hokkien and Minnanyu). The script should be traditional Chinese ("Hant"), not simplified Chinese ("Hans").

**Comment by kipcole9** [comment]
@logicmason Thanks for the report.   I know how CLDR rules end up with the definition you describe - but Im not sure yet how to resolve it.  Let me describe how the locale resolution happens and a couple of thoughts and perhaps you can give me your feedback?

### Locale lookup

When a locale name is validated there are a few steps involved:

1. If the locale name is directly known to Cldr then the appropriate language tag is returned.  In this case, neither the language `nan` nor the locale name `nan-TW` is defined in CLDR.

2. Then alias substitutions occurs.  This is mostly for mapping obsolete or deprecated locale names into the contemporary ones.  There is no alias for `nan` or `nan-TW`.  There is an alias for [zh-min-nan](https://github.com/unicode-cldr/cldr-core/blob/master/supplemental/aliases.json#L1315-L1318) but that isn't applied in your example.

3. Then there is substitution of likely subtags.  That is, for a given language (and potentially territory) what is the most likely script.  CLDR maintains a [set of sub tag substitutions](https://github.com/unicode-cldr/cldr-core/blob/master/supplemental/likelySubtags.json) which, for the locale name `nan` returns the language tag [nan-Hans-CN](https://github.com/unicode-cldr/cldr-core/blob/master/supplemental/likelySubtags.json#L866). For your example we now have `nan-Hans-CN`

4. Lastly any non-language components of the original locale name are substituted back into the language tag.  In this case the territory `TW` is put back and we end up with `nan-Hans-TW`.

### Some thoughts

As I'm sure you're aware there is no CLDR data for the locale "nan" or "nan-TW".  But of course that isn't necessarily relevant to your use case if you're parsing language tags or `Accept-Language` headers.  

1. The CLDR specification allows for overriding the script to be used in API calls.  Today my implementation does not allow that although its "on the list".  

2. I could manually maintain an additional set of aliases that would let you specify the transform for "nan-TW" to be "nan-Hant-TW".  I worry about the maintenance cost and technical debt.

3. Like (2) above, but allow a user to configure aliases.  I like this approach better than (2) for obvious reasons

4. Any other ideas?

### Next Steps

Let me know what you think would be an appropriate way forward and any ideas you might have around your use case?

**Comment by logicmason** [comment]
I see two issues. The more general one is that the alias substitution in step 2 is impossible to get right for Chinese languages since the script is dependent on territory more than topolect. I don't have a good suggestion about how to handle this though since there are many, many other locales to worry about in this project.

The more specific issue is the transformation in step 3 is almost certainly a poor one. Taiwan is the only place on earth where the Minnan language has official status, is taught in school or has widespread use in television, film or music. While it is spoken in Fujian province as well, the language has less standing in the PRC than Cantonese (Yue) does.

I noticed the substitutions for Cantonese are as follows:
 ```
"yue": "yue-Hant-HK",
"yue-CN": "yue-Hans-CN",
"yue-Hans": "yue-Hans-CN",
```
I believe it would make sense to use an analogous set of substitutions, such as the following for Taiwanese: 
```
 "nan": "nan-Hant-TW",
 "nan-CN": "nan-Hans-CN",
 "nan-Hans": "nan-Hans-CN",
```
Now that I understand this behavior is coming from a dependency, I'll close this issue and open one on the CLDR repo. Thanks for the explanation!

**Comment by kipcole9** [comment]
@logicmason its this repo :-)

I use Cldr to mean this repo and CLDR to mean the Unicode CLDR data repository.  I should have made that clear.

But given your knowledge is clearly way better than mine (he says in embarrassment living Singapore a long time, been to Taiwan a lot and lived in China for 2 years) are you saying that basically the Unicode CLDR repository is incorrect and the source data should be fixed?

If so, then yes, a ticket on the CLDR system would be appropriate.  Or may I suggest and email to `cldr-users@unicode.org` maybe the right place to get community support for your recommendations?

**Comment by kipcole9** [comment]
I should say there is always the possibility that I have a bug and that my implementation does not faithfully [implement TR35](http://unicode.org/reports/tr35/#Inheritance_and_Validity) for alias and sub tag substitutions but my tests are using TR35's documentation so I think its at least close!

Therefore if you write to the ` cldr-users@unicode.org` mailing list it would worth asking if its an implementation issue or a data definition issue.

If you'd prefer I'm more than happy to consult the Unicode community directly myself - but your domain knowledge suggests you can be more compelling in your argument.

**Comment by logicmason** [comment]
I think it is an error. I just stumbled across this while working on another project. I'm not sure if I'm in a position to do much advocacy, but I left a ticket outlining essentially the same recommendation I just made here.

**Comment by kipcole9** [comment]
Thanks much for that, it get strangely attached to code I write and when it doesn't deliver to expectations I feel compelled to fix it.  So thanks for filing the issue.  

I'll keep this issue open to remind me to check in the next release cycle of CLDR data (twice a year for main releases, occasional bug fix releases).

**Comment by kipcole9** [comment]
I can't see your bug report in the CLDR issues tracker - any change you could add the link to the issue you submitted here so I can keep track of its progress?

**Comment by kipcole9** [comment]
Regretably as of CLDR version 33 (latest version) this is still not corrected.

**Comment by kipcole9** [comment]
As of CLDR versions 35 and 35 this is still not fixed and there appears little sign it will be.  Therefore I will close this issue as `wontfix`.
