### ISSUE TITLE
Creating an elixir-cldr organization

### ISSUE THREAD

**Issue by Schultzer** [elixir-cldr/cldr#61]
Hi,

Would it be worth it to create an organization for `ex_cldr` and its supporting libraries?

#### Pros
* Code unification across libraries with `mix format`
* One CI for testing across the libraries
* We can help each other out and delegate responsibility
* Code reviews

I'm not sure about the cons, let me know what you think.

cc @kipcole9  @LostKobrakai

**Comment by kipcole9** [comment]
I create the organisation when I finalise all parts of the version 2.0 release cycle.  Its a good milestone to aim for!

**Comment by kipcole9** [comment]
Done now that [ex_cldr_dates_times](https://hex.pm/packages/ex_cldr_dates_times) has finally been updated. 

Moved all the `Cldr_*` repos to [elixir-cldr](https://github.com/elixir-cldr).  Thanks for the suggestion.
