### ISSUE TITLE
Remove nimble_parsec runtime dependency

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-cldr/cldr#99]
I'm wondering if we could remove the nimble_parsec dependency at runtime all together using: https://hexdocs.pm/nimble_parsec/Mix.Tasks.NimbleParsec.Compile.html#content

**Comment by kipcole9** [comment]
I've done some experimentation and whilst its works fine, it produces a *lot* of compiler warnings from the generated code:
```
Compiling 46 files (.ex)
warning: variable "acc" is unused
  lib/cldr/language_tag/rfc5646_parser.ex:340

warning: variable "acc" is unused
  lib/cldr/language_tag/rfc5646_parser.ex:404

warning: variable "acc" is unused
  lib/cldr/language_tag/rfc5646_parser.ex:425

warning: variable "acc" is unused
  lib/cldr/language_tag/rfc5646_parser.ex:516

warning: variable "context" is unused
  lib/cldr/language_tag/rfc5646_parser.ex:571

warning: variable "line" is unused
  lib/cldr/language_tag/rfc5646_parser.ex:571

# and a lot, lot more
```
And I feel that as a lib writer, lots of compiler warnings doesn't inspire confidence for a lib user.  Open to suggestions though.

**Comment by maennchen** [comment]
@kipcole9 This can probably be implemented since `nimble_parsec` had a few releases since then.
